"""Regenerate the UMG 604-PRO electrical float catalog from extracted PDF text.

Source: https://www.janitza.com/files/download/manuals/current/UMG604-PRO/janitza-mal-umg604pro-en.pdf
The input is the PDF's page text with 'PAGE <number>' markers (as emitted by
PDFKit). Only address/designation/unit facts are copied; labels are generated
by the application from the documented designations.
"""

import re
import sys
from pathlib import Path

source = Path(sys.argv[1]).read_text()
output = Path(sys.argv[2])
page = 0
rows = []
known_units = {'V', 'A', 'W', 'VA', 'VAr', 'Wh', 'VAh', 'VArh', 'Hz', '%', '°C', 'n', 's', 'var', 'varh'}
for line in source.splitlines():
    if line.startswith('PAGE '):
        page = int(line.split()[1])
    match = re.match(r'^\s*(\d{1,5})\s+float\s+(_[A-Za-z0-9_]+(?:\[\d+\])?)(.*)$', line)
    if not match:
        continue
    address = int(match[1])
    electrical = (
        (page in {12, 13} and 19000 <= address <= 19694)
        or (14 <= page <= 104 and address <= 9971)
        or (page == 108 and 14131 <= address <= 14163)
        or (page == 109 and 14404 <= address <= 14474)
        or (page == 115 and address in {15156, 15158, 15237, 15239, 15241, 15243})
        or (page == 116 and 19704 <= address <= 19708)
    )
    if not electrical:
        continue
    first = match[3].strip().split(maxsplit=1)
    unit = first[0] if first and first[0] in known_units else ''
    if 19704 <= address <= 19708:
        unit = '°'
    rows.append((address, match[2], unit))
for address, designation in re.findall(r'(\d{5})\s+float\s+(_P15_MONTH\[\d+\])', source):
    rows.append((int(address), designation, 'W'))
rows.sort()
assert len(rows) == 3295, len(rows)
assert len(set(address for address, _, _ in rows)) == len(rows)
assert (9851, '_WH_V[4]', 'Wh') in rows
lines = [
    '// UMG 604-PRO Modbus address list, firmware 5.028 and newer (Janitza, 08/2023).',
    '// Generated by scripts/generate-umg604-catalog.py from the official PDF.',
    '// Covers documented electrical float values, including harmonics, energy, quick values, and monthly demand.',
    '// Values are read on demand; discovery does not poll these registers.',
    'export const umg604CatalogRows: readonly (readonly [number, string, string])[] = [',
]
for address, designation, unit in rows:
    lines.append(f"  [{address}, '{designation}', '{unit}'],")
lines.append('];')
output.write_text('\n'.join(lines) + '\n')
print(f'wrote {len(rows)} rows to {output}')
